config {
  type: "view",
  schema: "query"
}


SELECT
  MD5(CONCAT(
        IFNULL(cast(ticket_id AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[0]') AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[1]') AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[2]') AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[3]') AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[4]') AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[5]') AS STRING), '')
    )) id
  ,ticket_id root_id
  ,last_update
  ,case
    when JSON_EXTRACT_SCALAR(json, '$[0]') = '' then NULL
    else JSON_EXTRACT_SCALAR(json, '$[0]')
  end khoan_muc_chi_phi
  ,case
    when JSON_EXTRACT_SCALAR(json, '$[1]') = '' then NULL
    else JSON_EXTRACT_SCALAR(json, '$[1]')
  end cach_tinh
  ,case
    when JSON_EXTRACT_SCALAR(json, '$[2]') = '' then NULL
    else JSON_EXTRACT_SCALAR(json, '$[2]')
  end ky_hieu
  ,case
    when JSON_EXTRACT_SCALAR(json, '$[3]') = '' then NULL
    else JSON_EXTRACT_SCALAR(json, '$[3]')
  end tong_gia_tri
FROM (
  SELECT
    (json_extract_array(value)) AS json_array
    ,ticket_id
    ,last_update
  FROM (SELECT ticket_id, last_update, CAST(FROM_BASE64(value) AS STRING) value FROM ${ref('raw_service_ticket_form')} job_form 
      WHERE keys = 'service_bang_tong_hop_gia_chao' 
            -- and type = 'input-table' 
            AND NOT REGEXP_CONTAINS(cast(value as string), r'[áàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵđÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬÉÈẺẼẸÊẾỀỂỄỆÍÌỈĨỊÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÚÙỦŨỤƯỨỪỬỮỰÝỲỶỸỴĐ]')
            AND cast(value as string) not like '%{}%'
            AND (value not like '%{}%') 
            AND (value not like '% %') 
            AND (value not like '%1.%'))
), UNNEST(json_array) AS json