name: kh_vbg
version: '1.0.0'
config-version: 2

profile: kh_vbg

model-paths: [models]
macro-paths: [macros]

clean-targets:
  - target
  - dbt_packages

models:
  kh_vbg:
    +persist_docs:
      relation: true
      columns: true
