config {
  type: "view",
  schema: "query"
}


SELECT
  MD5(CONCAT(
        IFNULL(cast(task_id AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[0]') AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[1]') AS STRING), ''),
        IFNULL(cast(JSON_EXTRACT_SCALAR(json, '$[2]') AS STRING), '')
    )) id
  ,task_id
  ,last_update
  ,case
    when JSON_EXTRACT_SCALAR(json, '$[0]') = '' then NULL
    else JSON_EXTRACT_SCALAR(json, '$[0]')
  end phong_ban
  ,case
    when JSON_EXTRACT_SCALAR(json, '$[1]') = '' then NULL
    else JSON_EXTRACT_SCALAR(json, '$[1]')
  end khoi_luong
  ,case
    when JSON_EXTRACT_SCALAR(json, '$[2]') = '' then NULL
    else JSON_EXTRACT_SCALAR(json, '$[2]')
  end gia_tri

FROM (
  SELECT
    (json_extract_array(value)) AS json_array
    ,task_id
    ,last_update
  FROM (SELECT task_id, last_update, CAST(FROM_BASE64(value) AS STRING) value FROM ${ref('raw_task_form')} job_form 
      WHERE name = '[KHVT] Kế hoạch công việc Tháng' 
            -- and type = 'input-table' 
            AND NOT REGEXP_CONTAINS(cast(value as string), r'[áàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵđÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬÉÈẺẼẸÊẾỀỂỄỆÍÌỈĨỊÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÚÙỦŨỤƯỨỪỬỮỰÝỲỶỸỴĐ]')
            AND cast(value as string) not like '%{}%'
            AND (value not like '%{}%') 
            AND (value not like '% %') 
            AND (value not like '%1.%'))
), UNNEST(json_array) AS json