config {
  type: "view",
  schema: "query"
}

SELECT
  CAST(JSON_EXTRACT_SCALAR(json, '$.id') AS INT64)  id
  ,task_id
  ,last_update
  ,JSON_EXTRACT_SCALAR(json, '$.name')  name
  ,CAST(JSON_EXTRACT_SCALAR(json, '$.creator_id') AS INT64)  creator_id
  ,CAST(JSON_EXTRACT_SCALAR(json, '$.user_id') AS INT64)  user_id
  ,CAST(JSON_EXTRACT_SCALAR(json, '$.review')  AS INT64) review
  ,CAST(JSON_EXTRACT_SCALAR(json, '$.status') AS INT64)  status
  ,CAST(TIMESTAMP_ADD(TIMESTAMP_SECONDS(CAST(JSON_EXTRACT_SCALAR(json, '$.deadline') AS INT64)), INTERVAL 7 HOUR) AS DATETIME) deadline
FROM ${ref('raw_task')},
  UNNEST(JSON_EXTRACT_ARRAY(cached_subtasks)) AS json
